name: team_collaboration_tool
description: A server app using the shelf package and Docker.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  args: ^2.0.0
  uuid: ^3.0.6
  drift: ^2.2.0
  path: ^1.8.2
  riverpod: ^2.0.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.15.0
  build_runner: ^2.2.1
  drift_dev: ^2.2.0+1
